jQuery(document).ready(function(){"use strict";erling_tm_modalbox();erling_tm_nav_bg();erling_tm_trigger_menu();erling_tm_modalbox_news();erling_tm_modalbox_portfolio();erling_tm_imgtosvg();erling_tm_popup();erling_tm_data_images();erling_tm_swiper();myAccordion();erling_tm_totop();jQuery(window).load('body',function(){erling_tm_my_load();});jQuery(window).on('scroll',function(){erling_tm_progress_line();});});function erling_tm_modalbox(){"use strict";jQuery('.erling_tm_all_wrap').prepend('<div class="erling_tm_modalbox"><div class="box_inner"><div class="close"><a href="#"><i class="icon-cancel"></i></a></div><div class="description_wrap"></div></div></div>');}
function erling_tm_nav_bg(){"use strict";jQuery(window).on('scroll',function(){var menu=jQuery('.erling_tm_header');var progress=jQuery('.progressbar');var WinOffset=jQuery(window).scrollTop();if(WinOffset>=100){menu.addClass('animate');progress.addClass('animate');}else{menu.removeClass('animate');progress.removeClass('animate');}});}
function tdProgress(container){"use strict";container.find('.progress_inner').each(function(){var progress=jQuery(this);var pValue=parseInt(progress.data('value'),10);var pColor=progress.data('color');var pBarWrap=progress.find('.bar');var pBar=progress.find('.bar_in');pBar.css({width:pValue+'%',backgroundColor:pColor});setTimeout(function(){pBarWrap.addClass('open');});});}
jQuery('.erling_progress').each(function(){"use strict";var pWrap=jQuery(this);pWrap.waypoint({handler:function(){tdProgress(pWrap);},offset:'90%'});});function erling_tm_trigger_menu(){"use strict";var audio1=jQuery('.audiowrap #audio1');var audio2=jQuery('.audiowrap #audio2');var hamburger=jQuery('.trigger .hamburger');var list=jQuery('.erling_tm_header .list ul li');var mobileMenu=jQuery('.erling_tm_mobile_menu .dropdown');var mobileMenuList=jQuery('.erling_tm_mobile_menu .dropdown .dropdown_inner ul li a');hamburger.on('click',function(){var element=jQuery(this);if(element.hasClass('is-active')){element.removeClass('is-active');if(jQuery('.audiowrap').length){audio1[0].play();}
list.removeClass('opened');mobileMenu.slideUp();}else{element.addClass('is-active');if(jQuery('.audiowrap').length){audio2[0].play();}
list.each(function(i){var ele=jQuery(this);setTimeout(function(){ele.addClass('opened');},i*50);});mobileMenu.slideDown();}
return false;});mobileMenuList.on('click',function(){jQuery('.trigger .hamburger').removeClass('is-active');mobileMenu.slideUp();return false;});}
function erling_tm_modalbox_news(){"use strict";var modalBox=jQuery('.erling_tm_modalbox');var button=jQuery('.erling_tm_news .erling_tm_full_link, .erling_tm_news .news_list ul li .title a');var closePopup=modalBox.find('.close');button.on('click',function(){var element=jQuery(this);var parent=element.closest('li');var content=parent.find('.news_hidden_details').html();var image=parent.find('.image .main').data('img-url');var meta=parent.find('.details .meta').html();var title=parent.find('.details .title a').text();var date=parent.find('.date').text();modalBox.addClass('opened');modalBox.find('.description_wrap').html(content);modalBox.find('.news_popup_informations').prepend('<div class="image"><img src="img/thumbs/4-2.jpg" alt="" /><div class="main" data-img-url="'+image+'"></div></div>');modalBox.find('.news_popup_informations .image').append('<span class="date">'+date+'</span>');modalBox.find('.news_popup_informations .image').after('<div class="details_news"><div class="meta">'+meta+'</div><div class="title"><h3>'+title+'</h3></div></div>');erling_tm_data_images();return false;});closePopup.on('click',function(){modalBox.removeClass('opened');modalBox.find('.description_wrap').html('');return false;});}
function erling_tm_modalbox_portfolio(){"use strict";var modalBox=jQuery('.erling_tm_modalbox');var button=jQuery('.erling_tm_portfolio .portfolio_popup');button.on('click',function(){var element=jQuery(this);var parent=element.closest('.list_inner');var image=parent.find('.image .main').data('img-url');var details=parent.find('.hidden_content_portfolio').html();var title=parent.find('.details h3').text();var category=parent.find('.details span').text();modalBox.addClass('opened');modalBox.find('.description_wrap').html(details);modalBox.find('.popup_details').prepend('<div class="top_image"><img src="img/thumbs/4-2.jpg" alt="" /><div class="main" data-img-url="'+image+'"></div></div>');modalBox.find('.popup_details .top_image').after('<div class="portfolio_main_title"><h3 class="title">'+title+'</h3><span class="category"><a href="#">'+category+'</a></span></div>');erling_tm_data_images();return false;});}
function erling_tm_preloader(){"use strict";var isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)?true:false;var preloader=$('#preloader');if(!isMobile){setTimeout(function(){preloader.addClass('preloaded');},800);setTimeout(function(){preloader.remove();},2000);}else{preloader.remove();}}
function erling_tm_my_load(){"use strict";var speed=500;setTimeout(function(){erling_tm_preloader();},speed);setTimeout(function(){jQuery('.erling_tm_all_wrap').addClass('ready');},speed+2000);}
function erling_tm_imgtosvg(){"use strict";jQuery('img.html').each(function(){var jQueryimg=jQuery(this);var imgClass=jQueryimg.attr('class');var imgURL=jQueryimg.attr('src');jQuery.get(imgURL,function(data){var jQuerysvg=jQuery(data).find('svg');if(typeof imgClass!=='undefined'){jQuerysvg=jQuerysvg.attr('class',imgClass+' replaced-svg');}
jQuerysvg=jQuerysvg.removeAttr('xmlns:a');jQueryimg.replaceWith(jQuerysvg);},'xml');});}
function erling_tm_popup(){"use strict";jQuery('.gallery_zoom').each(function(){jQuery(this).magnificPopup({delegate:'a.zoom',type:'image',gallery:{enabled:true},removalDelay:300,mainClass:'mfp-fade'});});jQuery('.popup-youtube, .popup-vimeo').each(function(){jQuery(this).magnificPopup({disableOn:100,type:'iframe',mainClass:'mfp-fade',removalDelay:160,preloader:false,fixedContentPos:true});});jQuery('.soundcloude_link').magnificPopup({type:'image',gallery:{enabled:true,},});}
function erling_tm_data_images(){"use strict";var data=jQuery('*[data-img-url]');data.each(function(){var element=jQuery(this);var url=element.data('img-url');element.css({backgroundImage:'url('+url+')'});});}
jQuery('.anchor_nav').onePageNav();new WOW().init();function erling_tm_swiper(){"use strict";$('.swiper-section').each(function(){var element=$(this);var container=element.find('.swiper-container');var mySwiper=new Swiper(container,{loop:false,slidesPerView:1,spaceBetween:0,loopAdditionalSlides:1,autoplay:{delay:6000,},navigation:{nextEl:'.my_next',prevEl:'.my_prev',},pagination:{el:'.erling_tm_swiper_progress',type:'custom',renderCustom:function(swiper,current,total){var scale,translateX;var progressDOM=container.find('.erling_tm_swiper_progress');if(progressDOM.hasClass('fill')){translateX='0px';scale=parseInt((current/total)*100)/100;}else{scale=parseInt((1/total)*100)/100;translateX=(current-1)*parseInt((100/total)*100)/100+'px';}
progressDOM.find('.all span').css({transform:'translate3d('+translateX+',0px,0px) scaleX('+scale+') scaleY(1)'});if(current<10){current='0'+current;}
if(total<10){total='0'+total;}
progressDOM.find('.current').html(current);progressDOM.find('.total').html(total);}},breakpoints:{700:{slidesPerView:2,spaceBetween:20,},1200:{slidesPerView:3,spaceBetween:40,}}});});erling_tm_imgtosvg();}
function myAccordion(){"use strict";jQuery('.accordion_wrap').removeClass('ready');jQuery('.accordion.active').each(function(){jQuery(this).find('.accordion_content').css({display:'block'});});var button=jQuery('.accordion_wrap .accordion_header');button.on('click',function(){var element=jQuery(this);var li=element.closest('.accordion');if(li.hasClass('active')){li.removeClass('active').find('.accordion_content').slideUp();}else{li.siblings('.active').removeClass('active').find('.accordion_content').slideUp();li.addClass('active').find('.accordion_content').slideDown();}
return false;});}
function erling_tm_progress_line(){"use strict";var line=jQuery('.progressbar .line');var documentHeight=jQuery(document).height();var windowHeight=jQuery(window).height();var winScroll=jQuery(window).scrollTop();var value=(winScroll/(documentHeight-windowHeight))*100;var position=value;line.css('height',position+"%");}
function erling_tm_totop(){"use strict";var text=$('.progressbar .text');text.css({bottom:105+text.width()});$(".progressbar a").on('click',function(e){e.preventDefault();$("html, body").animate({scrollTop:0},'slow');return false;});}